---
 - name: Install python dependencies
   yum: 
     name:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - python-mysqldb
     state: present