---
 - name: Install python dependencies
   yum: name= "{{ item }}" state=installed
   with_items:
    - { name: python }
    - { name: python-setuptools }
    - { name: python-dev }
    - { name: build-essential }
    - { name: python-pip }
    - { name: python-mysqldb }
